version: '3'

tasks:
  run:
    cmds:
      - uv run -m template_py.main
  check:
    deps:
      - typecheck
      - lint
  typecheck:
    cmds:
      - uv run pyright src
  lint:
    cmds:
      - uv run ruff check src
  format:
    cmds:
      - uv run ruff format src
  test:
    cmds:
      - uv run pytest
  audit:
    cmds:
      - uv run --all-groups pip-audit
